export interface IBibleBook {
  id: string;
  name: string;
  otherNames?: string[];
  order: number;
  numberOfChapters: number;
  totalNumberOfVerses: number;
}

const books: IBibleBook[] = [
  {
    id: "GEN",
    name: "Genesis",
    order: 1,
    numberOfChapters: 50,
    totalNumberOfVerses: 1533,
  },
  {
    id: "EXO",
    name: "Exodus",
    order: 2,
    numberOfChapters: 40,
    totalNumberOfVerses: 1213,
  },
  {
    id: "LEV",
    name: "Leviticus",
    order: 3,
    numberOfChapters: 27,
    totalNumberOfVerses: 859,
  },
  {
    id: "NUM",
    name: "Numbers",
    order: 4,
    numberOfChapters: 36,
    totalNumberOfVerses: 1288,
  },
  {
    id: "DEU",
    name: "Deuteronomy",
    order: 5,
    numberOfChapters: 34,
    totalNumberOfVerses: 959,
  },
  {
    id: "JOS",
    name: "Joshua",
    order: 6,
    numberOfChapters: 24,
    totalNumberOfVerses: 658,
  },
  {
    id: "JDG",
    name: "Judges",
    order: 7,
    numberOfChapters: 21,
    totalNumberOfVerses: 618,
  },
  {
    id: "RUT",
    name: "Ruth",
    order: 8,
    numberOfChapters: 4,
    totalNumberOfVerses: 85,
  },
  {
    id: "1SA",
    name: "1 Samuel",
    order: 9,
    numberOfChapters: 31,
    totalNumberOfVerses: 810,
  },
  {
    id: "2SA",
    name: "2 Samuel",
    order: 10,
    numberOfChapters: 24,
    totalNumberOfVerses: 695,
  },
  {
    id: "1KI",
    name: "1 Kings",
    order: 11,
    numberOfChapters: 22,
    totalNumberOfVerses: 816,
  },
  {
    id: "2KI",
    name: "2 Kings",
    order: 12,
    numberOfChapters: 25,
    totalNumberOfVerses: 719,
  },
  {
    id: "1CH",
    name: "1 Chronicles",
    order: 13,
    numberOfChapters: 29,
    totalNumberOfVerses: 942,
  },
  {
    id: "2CH",
    name: "2 Chronicles",
    order: 14,
    numberOfChapters: 36,
    totalNumberOfVerses: 822,
  },
  {
    id: "EZR",
    name: "Ezra",
    order: 15,
    numberOfChapters: 10,
    totalNumberOfVerses: 280,
  },
  {
    id: "NEH",
    name: "Nehemiah",
    order: 16,
    numberOfChapters: 13,
    totalNumberOfVerses: 406,
  },
  {
    id: "EST",
    name: "Esther",
    order: 17,
    numberOfChapters: 10,
    totalNumberOfVerses: 167,
  },
  {
    id: "JOB",
    name: "Job",
    order: 18,
    numberOfChapters: 42,
    totalNumberOfVerses: 1070,
  },
  {
    id: "PSA",
    name: "Psalms",
    otherNames: ["Psalms", "Psalm", "Psa", "Psm"],
    order: 19,
    numberOfChapters: 150,
    totalNumberOfVerses: 2461,
  },
  {
    id: "PRO",
    name: "Proverbs",
    order: 20,
    numberOfChapters: 31,
    totalNumberOfVerses: 915,
  },
  {
    id: "ECC",
    name: "Ecclesiastes",
    order: 21,
    numberOfChapters: 12,
    totalNumberOfVerses: 222,
  },
  {
    id: "SNG",
    name: "Song",
    order: 22,
    numberOfChapters: 8,
    totalNumberOfVerses: 117,
  },
  {
    id: "ISA",
    name: "Isaiah",
    order: 23,
    numberOfChapters: 66,
    totalNumberOfVerses: 1292,
  },
  {
    id: "JER",
    name: "Jeremiah",
    order: 24,
    numberOfChapters: 52,
    totalNumberOfVerses: 1364,
  },
  {
    id: "LAM",
    name: "Lamentations",
    order: 25,
    numberOfChapters: 5,
    totalNumberOfVerses: 154,
  },
  {
    id: "EZK",
    name: "Ezekiel",
    order: 26,
    numberOfChapters: 48,
    totalNumberOfVerses: 1273,
  },
  {
    id: "DAN",
    name: "Daniel",
    order: 27,
    numberOfChapters: 12,
    totalNumberOfVerses: 357,
  },
  {
    id: "HOS",
    name: "Hosea",
    order: 28,
    numberOfChapters: 14,
    totalNumberOfVerses: 197,
  },
  {
    id: "JOL",
    name: "Joel",
    order: 29,
    numberOfChapters: 3,
    totalNumberOfVerses: 73,
  },
  {
    id: "AMO",
    name: "Amos",
    order: 30,
    numberOfChapters: 9,
    totalNumberOfVerses: 146,
  },
  {
    id: "OBA",
    name: "Obadiah",
    order: 31,
    numberOfChapters: 1,
    totalNumberOfVerses: 21,
  },
  {
    id: "JON",
    name: "Jonah",
    order: 32,
    numberOfChapters: 4,
    totalNumberOfVerses: 48,
  },
  {
    id: "MIC",
    name: "Micah",
    order: 33,
    numberOfChapters: 7,
    totalNumberOfVerses: 105,
  },
  {
    id: "NAM",
    name: "Nahum",
    order: 34,
    numberOfChapters: 3,
    totalNumberOfVerses: 47,
  },
  {
    id: "HAB",
    name: "Habakkuk",
    order: 35,
    numberOfChapters: 3,
    totalNumberOfVerses: 56,
  },
  {
    id: "ZEP",
    name: "Zephaniah",
    order: 36,
    numberOfChapters: 3,
    totalNumberOfVerses: 53,
  },
  {
    id: "HAG",
    name: "Haggai",
    order: 37,
    numberOfChapters: 2,
    totalNumberOfVerses: 38,
  },
  {
    id: "ZEC",
    name: "Zechariah",
    order: 38,
    numberOfChapters: 14,
    totalNumberOfVerses: 211,
  },
  {
    id: "MAL",
    name: "Malachi",
    order: 39,
    numberOfChapters: 4,
    totalNumberOfVerses: 55,
  },
  {
    id: "MAT",
    name: "Matthew",
    order: 40,
    numberOfChapters: 28,
    totalNumberOfVerses: 1068,
  },
  {
    id: "MRK",
    name: "Mark",
    order: 41,
    numberOfChapters: 16,
    totalNumberOfVerses: 673,
  },
  {
    id: "LUK",
    name: "Luke",
    order: 42,
    numberOfChapters: 24,
    totalNumberOfVerses: 1149,
  },
  {
    id: "JHN",
    name: "John",
    order: 43,
    numberOfChapters: 21,
    totalNumberOfVerses: 878,
  },
  {
    id: "ACT",
    name: "Acts",
    order: 44,
    numberOfChapters: 28,
    totalNumberOfVerses: 1003,
  },
  {
    id: "ROM",
    name: "Romans",
    order: 45,
    numberOfChapters: 16,
    totalNumberOfVerses: 432,
  },
  {
    id: "1CO",
    name: "1 Corinthians",
    order: 46,
    numberOfChapters: 16,
    totalNumberOfVerses: 437,
  },
  {
    id: "2CO",
    name: "2 Corinthians",
    order: 47,
    numberOfChapters: 13,
    totalNumberOfVerses: 257,
  },
  {
    id: "GAL",
    name: "Galatians",
    order: 48,
    numberOfChapters: 6,
    totalNumberOfVerses: 149,
  },
  {
    id: "EPH",
    name: "Ephesians",
    order: 49,
    numberOfChapters: 6,
    totalNumberOfVerses: 155,
  },
  {
    id: "PHP",
    name: "Philippians",
    order: 50,
    numberOfChapters: 4,
    totalNumberOfVerses: 104,
  },
  {
    id: "COL",
    name: "Colossians",
    order: 51,
    numberOfChapters: 4,
    totalNumberOfVerses: 95,
  },
  {
    id: "1TH",
    name: "1 Thessalonians",
    order: 52,
    numberOfChapters: 5,
    totalNumberOfVerses: 89,
  },
  {
    id: "2TH",
    name: "2 Thessalonians",
    order: 53,
    numberOfChapters: 3,
    totalNumberOfVerses: 47,
  },
  {
    id: "1TI",
    name: "1 Timothy",
    order: 54,
    numberOfChapters: 6,
    totalNumberOfVerses: 113,
  },
  {
    id: "2TI",
    name: "2 Timothy",
    order: 55,
    numberOfChapters: 4,
    totalNumberOfVerses: 83,
  },
  {
    id: "TIT",
    name: "Titus",
    order: 56,
    numberOfChapters: 3,
    totalNumberOfVerses: 46,
  },
  {
    id: "PHM",
    name: "Philemon",
    order: 57,
    numberOfChapters: 1,
    totalNumberOfVerses: 25,
  },
  {
    id: "HEB",
    name: "Hebrews",
    order: 58,
    numberOfChapters: 13,
    totalNumberOfVerses: 303,
  },
  {
    id: "JAS",
    name: "James",
    order: 59,
    numberOfChapters: 5,
    totalNumberOfVerses: 108,
  },
  {
    id: "1PE",
    name: "1 Peter",
    order: 60,
    numberOfChapters: 5,
    totalNumberOfVerses: 105,
  },
  {
    id: "2PE",
    name: "2 Peter",
    order: 61,
    numberOfChapters: 3,
    totalNumberOfVerses: 61,
  },
  {
    id: "1JN",
    name: "1 John",
    order: 62,
    numberOfChapters: 5,
    totalNumberOfVerses: 105,
  },
  {
    id: "2JN",
    name: "2 John",
    order: 63,
    numberOfChapters: 1,
    totalNumberOfVerses: 13,
  },
  {
    id: "3JN",
    name: "3 John",
    order: 64,
    numberOfChapters: 1,
    totalNumberOfVerses: 14,
  },
  {
    id: "JUD",
    name: "Jude",
    order: 65,
    numberOfChapters: 1,
    totalNumberOfVerses: 25,
  },
  {
    id: "REV",
    name: "Revelation",
    order: 66,
    numberOfChapters: 22,
    totalNumberOfVerses: 404,
  },
];

export default books;